### ISSUE TITLE
Create platform tutorial

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#128]
Create new sessions to define:

- What is a session?
- What is the test case?
- What is a pass/fail result?

Others to follow, @eudisley please add in the comments the other points you would like to add.

**Comment by eudisley** [comment]
Hi @agalaguz 
Since you are doing another documentation for the ITP Architecture, do not consider my previous comments. 

What it could be added here is:
- What is a session 
- How to create a Session
- What is the Test Case? 
- How to run test case and how it is executed (if possible show a flow)?
- How to understand the results? What results should the user expect?
- What is a pass/fail result?

You can use a doc file and I can pass to markdown.

**Comment by brunosmm** [comment]
@eudisley should we mirror the user manual to the tutorial page or add a link to the docs?
