### ISSUE TITLE
Find a way to manage negative scenarios via Test Cases instead of hardcoding them in Simulators (exampels inside)

### ISSUE THREAD

**Issue by agalaguz** [gsmainclusivetechlab/interop-test-platform#150]
The negative scenarios in Test-Case-driven platform should be managed on Test Case level.
Right now some Negative and Positive Cases cannot be managed on Test Case (TC) level (using overriding).

They are following the next rules:

- Any Endpoint in TC flow is different from the positive flow. e.g. `POST /quotes/{ID}/error` instead of  `PUT /quotes/{ID}` in [Rejected Quote by Payee FSP](http://prntscr.com/sfhh9i)   
- Additional Endpoints in TC flow. e.g. `GET /participants/{TYPE}/{ID}` and `PUT /participants/{TYPE}/{ID}` in [Authorized Transaction by Payer FSP with Account Lookup](http://prntscr.com/sfhiy7)   

Other found items to be added here by the team.

The list of Test Cases that requires "hardcode" in Simulators:

**A) Merchant-Initiated Merchant Payment**

1. [Rejected Quote by Payee FSP](http://prntscr.com/sfhh9i) -> **Amount == 51.03** in **MMO1** to send `POST /quotes/{ID}/error` instead of  `PUT /quotes/{ID}`
2. [Authorized Transaction by Payer FSP with Account Lookup](http://prntscr.com/sfhiy7) -> **Defined phone number** in **MMO1** and **Mojaloop** to send `GET /participants/{TYPE}/{ID}` and `PUT /participants/{TYPE}/{ID}` after `POST /trascations`
3. [Rejected Transaction by Payer FSP](http://prntscr.com/sfhr4l) -> **Amount == 10.1** in **MMO2** to send `PUT /transactonRequests/{ID}` instead of  `POST /transfers`

**Comment by brunosmm** [comment]
As discussed we will make the simulators more generic to be possible to support other errors and use the override in the test cases to change the values.

MMO1 Rules:
1.  Amount IN range (3000-3999) or (5000-5099), this rule will be used for error endpoints in any used case.
  - Check the last message received and generate an error for that endpoint.
  - Examples: 
    - If receive a POST/quotes with amount 3478, will generate next PUT/quotes/{ID}/Error;
    - If receive a POST/quotes with amount 5643, will generate next PUT/quotes/{ID}/Error;
    - If receive a POST/transfer with amount 4432, will generate next PUT/transfer/{ID}/Error;
    - If receive a POST/transfer with amount 3478, will generate next PUT/transfer/{ID}/Error;
    - If receive a POST/XXXX with amount 3478, will generate next PUT/XXXX/{ID}/Error;

2.  **Range** phone number in MMO1 and Mojaloop to send GET /participants/{TYPE}/{ID} and PUT /participants/{TYPE}/{ID} after POST /trascations
 - Do not need to add all possible numbers to Moja, add 1 number for each range.
 - Range to be added: 
   - +XX1XXX99XX
   - +XX2XXX99XX
   - +XX3XXX99XX
   - +XX4XXX99XX
   - +XX5XXX99XX
   - +XX6XXX99XX
   - +XX7XXX99XX
   - +XX8XXX99XX
   - +XX9XXX99XX

MMO2 Rules:
1.  Amount IN range (1000-1399), this rule will be used for Merchant Payment Flow to rejected a transaction
  - Check the last message received, if it was a PUT/quotes, Send PUT /transactonRequests/{ID} instead of POST /transfers
  - Examples: 
    - If receive a PUT/quotes with amount 1111, will generate next PUT /transactonRequests/{ID} 
    - If receive a PUT/quotes with amount 1234, will generate next PUT /transactonRequests/{ID} 

2.  Amount IN range (2000-2399), this rule will be used for Merchant Payment Flow to perform OTP verification
  - Check the last message received, if it was a PUT/quotes, Send POST /Authorization instead of POST /transfers
  - Examples: 
    - If receive a PUT/quotes with amount 2087, will generate next PUT /Authorization/
    - If receive a PUT/quotes with amount 2344, will generate next PUT /Authorization/

**Comment by brunosmm** [comment]
@eudisley can you add some test case files to test those SImulators rules?

**Comment by eudisley** [comment]
Just one observation. 
When you say amount from 5000 to 5099 it is actually 50.00 - 50.99

**Comment by brunosmm** [comment]
Thanks @eudisley, I change in the comment.

**Comment by agalaguz** [comment]
Hey guys, @eudisley @brunosmm 
It seem that the MMO2 Rules for P2P rejected actions (similar to ones that MMO1 has), e.g.
- If receive a POST/quotes with amount xx.xx, will generate next PUT/quotes/{ID}/Error;
- If receive a POST/transfer with amount xx.xx, will generate next PUT/transfer/{ID}/Error;
could you please suggest which ranges should we use?
or we may use thase same  (30.00-39.99) for quotes and (50.00-50.99) for transfers?

**Comment by eudisley** [comment]
I think we can use the same.
