### ISSUE TITLE
mTLS for outgoing requests

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#300]
As a platform user, I want to be able to test that my SUT correctly handles encrypted messages.

- During session creation, it should be possible to define whether the test session should mTLS message encryption.
- If encryption is enabled, all messages leaving the platform should be made via an mTLS connection. Note that this includes both outbound simulator messages _and_ messages which we are forwarding from one SUT to another SUT. 

## Requirements

- `test_step`s within a test case need a new field called `mTLS: true` (or false). If it is true, the request should be made using an mTLS connection instead of a standard HTTP connection. This setup allows us to have both "Encrypted" and "Uncrypted" versions of a test case (which will be selected by the user during the questionnaire).

## Discussion

mTLS is a [Network Layer](https://en.wikipedia.org/wiki/OSI_model#Layer_3:_Network_Layer) protocol, so we don't need to adjust anything in the message payload. Instead, we need to set up an HTTPS (mTLS) connection to the remote server and use that to send our payload. curl (and GuzzleHTTP) should manage that complexity for us. The main thing to bear in mind is that Mojaloop requires *m*TLS (i.e. *mutual* TLS, which is slightly more complicated than simple TLS). The crucial difference is that the client making the request (i.e. our code) also needs to present a certificate, rather than simply checking the remote server's certificate. The basic idea (as I understand it) is:

- We set up a Certificate Authority (CA) certificate and key
- We create a Client certificate and key, and sign the Client certificate with the CA. 
- We share our CA certificate with clients (i.e. with Mojaloop hub) so that they know to trust our Client certificate. [1]
- We fetch CA certificates from our clients (i.e. Mojaloop hub and DFSPs) so that we know to trust their responses. [2]
- We configure curl to use the Client certificate and key to encrypt requests, and to use the retrieved Server certificates to decrypt/validate the responses.

This is a fairly common scenario to implement, and there are many resources explaining how to do so (see below) - often under the term "Client Certificate Verification". The nuance is in distributing certificates ([1] and [2] above). 

### Distribution
[1]. Our CA certificate should not change very often. We can share it manually with the Mojaloop hub (via MCM for Mowali). 
[2]. Mojaloop CA certificate will be again be unchanging, but we still need a system for DFSP certificates to be shared with us. I can think of three options:
  ~(a). DFSPs upload their certificates to Modusbox Connection Manager (MCM), and ITP fetches them automatically. This is a smooth experience for the DFSP because it mirrors the "normal" onboarding process, but it would require us to have "hub" access to the MCM api.~ (this requires too much work)
  (b). DFSPs upload the certificates into the platform somewhere. This probably makes most sense at the group level.
  (c). Platform admins collect the certificate from externally (E.g.  MCM) and uploades them into the platform somewhere. 

Both options b and c can be combined to allow either platform admins or DFSPs to upload certificates themselves, depending on the preferred workflow for the environment. Note that there is _significant_ overlap in the certificate management part of this issue with #298 

## References

- [Stackoverflow answer on client certificates with curl in php](https://stackoverflow.com/questions/11308270/using-curl-in-php-with-client-certificate-and-private-key-in-separate-files)
- Modusbox Connection Manager User Guide (pdf from Mowali)
- [Modusbox Connection Manager API repository](https://github.com/modusbox/connection-manager-api) (in particular the swagger file describes all relevant endpoints)
- [Mojaloop encryption documentation](https://docs.mojaloop.io/mojaloop-specification/documents/Encryption.html)

**Comment by agalaguz** [comment]
Hi Christopher, @cjol 
Just wanted to ask how complicated encrytpion/decryption algorithm should be.
Will 'encryption' of the whole body message (i.e. all its fields) be enough, or some additional way to define what exactly fields from message should be encrytpted (e.g. via TC sytrax) is expected?

Could you please advise?

**Comment by cjol** [comment]
Hi Anton,

Thanks for checking. The issue as I initially described it is a little out of date, as my understanding has now developed. We don't need any custom encryption - we just need to set up a mTLS connection to the target component, and send the payload via that connection.

For some context, please see the updated issue for incoming requests: https://github.com/gsmainclusivetechlab/interop-test-platform/issues/298

I will try to update this current issue now to better reflect my new understanding.

**Comment by agalaguz** [comment]
Hi Christopher, @cjol 

Thank you for your comments. So, we are to start working on mTLS connection (issues #298 and #300).
Meantime, if we are to have the whole connection encrypted, will #299 still be required or it is out of date?
Thanks.

**Comment by cjol** [comment]
#299 is unfortunately still required, but may require an update. JWS is used by Mojaloop to prove that the payload is unmodified, in addition to mTLS encryption.

**Comment by agalaguz** [comment]
Hi Christopher, @cjol 

Just wanted to sum up these tasks #298 and #300 a bit. A few conclusions are below: 

1) Users can upload multiple certificates on a group level (_e.g. for staging, release, productions servers_)
2) User can select one of the group certificates on session configuration level or add a new one (similar to what we do with [env. variables](http://prntscr.com/w3t0al)) 
3) mTLS connection should be available for all types of sessions (_Test, Test + Questionnaire, and Compliance_)
4) User can select or add a new certificate for [every SUT](http://prntscr.com/w3u6q8) within the session  
5) Only messages from/to SUTs to use mTLS connection, messages between 'simulators' are be generated like they are. (_e.g. MMO1 is a SUT - so we use mTLS connection for messages from/to it. Messages between Moja and MMO2 are being generated by ITP based on `request` and `response` of TC, so no need to do something with them_.)

Some questions:

1) Why `mTLS: true` to be set per Test Step rather than to TC? Is that to allow _e.g. MMO1 as SUT to send `POST /quotes` via mTLS and `POST /transfers` via HTTP_? Just trying to understand 'use cases' for it. 
2) If TC includes step `POST /quotes` as `mTLS: true` but SUT sends it using HTTP - should ITP return some 'please use mTLS' message and fail Test Runs? Same for a case where `mTLS: false`, but mTLS is used?

**Comment by cjol** [comment]
Hi @agalaguz, I think your summary is accurate. Answering your questions:

1. That's exactly right - for example the Mobile Money API does not support mTLS connections, but the Mojaloop API does. So MMO1 as a SUT will need to communicate with SP over HTTP, and with Mojaloop over mTLS. It's possible that we could define this at the `components` level instead of at the test step level, but I think that will be more complicated?
2. 
   1. If a SUT sends a message using HTTP but the step is marked as `mTLS: true`, then the message should be accepted and the test continued, but a failure should be marked on the test step. 
   2. If a SUT sends a message using mTLS but the step is marked as `mTLS: false`, then the message should be accepted and the test continued _without_ marking a failure on the test step. N.B. I'm not 100% sure if this is the right behaviour, so in future we might revert this to mark a failure in this scenario.

**Comment by agalaguz** [comment]
Hi Christopher, @cjol 

Just a few notes on the technical side of this work. We discussed it internally and, seems like the next approach should help us to reach declared goals:

---

**Server-side changes**:
1. Server nginx should be removed from the server. All clients requests will be handled by nginx in docker-compose stack.
2. Certbot should be removed from the server and installed in docker-composer stack. SSL certs will be configured inside docker-compose stack.

These steps are required to make mTLS usage possible and avoid making any server-side configurations.
All mTLS actions and configurations should be implemented in docker-compose stack.

**docker-stack changes**:
1. SSL configuration for prod\staging or other installations with valid domains will be configured by `certbot` in docker-compose stack
2. `etc/nginx/clients-CA.crt` will be used by nginx to perform mTLS check
3. `client-ca-update.sh` will be added to cron. Script should be run every minute. `client-ca-update.sh` needed to perform CA.crt file update and nginx reload
4. Nginx will be reconfigured to allow mTLS

**basic algorithm**:
1. Laravel gets client CA cert and store it in some directory.
2. cron runs `client-ca-update.sh`
3. client-ca-update.sh checks directory with client CA cert
4. If CA cert exists - script wil add it in` /etc/nginx/clients-CA.crt` and gracefully reload nginx

---

This is a high-level plan that we are to implement in order to allow mTLS connections. Some specifics of it to be defined during the actual implementation (we are working on it now).

Hope this plan makes sense to you, please let us know if you have any comments. That will be much appreciated.

**Comment by cjol** [comment]
Hi Anton, this all makes sense to me, and I think it's a perfectly sound approach. My only thoughts:

 - running the cronjob every minute might be more than is necessary, since the changes to the CA file will be very infrequent. If it's very lightweight then it's okay, but otherwise I'd be happy to run it even every hour (if we ever need an urgent deploy of a certificate, we can always log in to the container to run the script manually).
 - As far as possible, let's try to keep `docker-compose` with environment-generic configuration, and specify specifics for prod/staging/other installations through env files. If this turns out not to be possible for some reasons, then it's probably okay but I'd love to discuss it before it gets added.

I know that this is a big, complicated task so I'm thankful for your time on it!
