### ISSUE TITLE
Component URI variables are not robust to name change

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#358]
This is the code that creates the URI variables (e.g. `SP_BASE_URI`). 
https://github.com/gsmainclusivetechlab/interop-test-platform/blob/39a88b438ec42eff2aef6aefa14460637c4b4468/src%2Fapp%2FModels%2FSession.php#L207-L230

It looks up the components using the component name, which will break if I e.g. change the name of "Mobile Money Operator 1" to "DFSP 1". Relatedly, if I remove a component (e.g. "Service Provider", which is not used in pure-Mojaloop environments), this code causes a crash on every test run. 

I propose two solutions: 
 - In the short term, these environment variables should be dynamically generated. Get all components from the DB, and generate variables of the form `"BASE_URI_" + UpperSnakeCase($component->name())`.
 - In the world with twig templating, these environment variables could be removed, and we would instead add twig functions `{{ componentURIByName('Service Provider') }}` and `{{ componentURIByUUID('ef60befa-1399-4c2a-93a6-0ff358eeee88') }}`

**Comment by agalaguz** [comment]
Hi Christopher, @cjol 
Thank you for raising this issue. 
Just wanted to ensure that all possible linked things are covered.

We are thinking about a bit different way to the short term solution that you suggested above, i.e.
> In the short term, these environment variables should be dynamically generated. Get all components from the DB, and generate variables of the form `"BASE_URI_" + UpperSnakeCase($component->name())`

Names like "Service Provider" are also used in the '[Components](http://prntscr.com/w7n2tn)' section of Test Cases. So, if we e.g. change the Component's name from "Mobile Money Operator 1" to "DFSP 1", we'll need to change it in Test Cases respectively.
In order not to edit all test cases after one of the "default" Component's name is changed we suggest:
- Add some value like `type` or `slug` for "default" Components so it instead of the name will be used to generate `BASE_URI`s
- `type` or `slug` to be used in test cases as "[component connector](http://prntscr.com/w7on83)" further (at least for new test cases, as TC from `/seeds` will be assigned to 'default' components once the platform is set up)
- Add some rules that prevent code crash if any of the Components are removed
- Use `"BASE_URI_" + UpperSnakeCase($component->name())` for all NEW Components

Could you please let me know if this works for you?

**Comment by cjol** [comment]
That makes sense. Just to check I understand: for example if the slug for "Mobile Money Operator 1" is `"mmo-1"`, the TC yaml would look like:

```yaml
components:
    - service-provider
    - mmo-1
    - mojaloop
    - mmo-2
test_steps:
   - path: /transactions
     source: service-provider
     target: mmo-1
```

For the variables, I would then suggest that we inject a `components` variable using twig that would be keyed using the slug directly, e.g.: 

```yaml
headers:
   Content-Type: application/json
   X-Callback-URL: {{ components["mmo-1"].base_uri }}
```

How big a change do you think this is? My guess is that it's not huge, and if that's the case then I am happy to wait for Twig templating to be ready, and not waste time with the intermediate `"BASE_URI_" + UpperSnakeCase($component->name())` solution. I'm not sure if this is what you meant, but I would also suggest that we include a "slug" field on the "Create Component" form (but not editable on the edit component field) so that we can treat default and new components in the same way.

**Comment by cjol** [comment]
I also am not too worried about conflicts within the default test cases. If someone has deleted or renamed a component, it's kind of their responsibility to also delete the test cases which use that component! The slug approach makes it easier for them to do so, so I am nonetheless in favour of it. The problem at the moment is that the snippet of code I included in the OP is run for _every_ test case, so even if I have deleted all the default test cases, it still causes an error.
