### ISSUE TITLE
Enable admins to download the API specs

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#419]
As admin role, I want to be able to be able to download the API specs from the platform

Tasks:

-   [ ] Add one more link on the menu to be possible download the API Spec YAML.

Requirements:

In the screen below enable the admin to download the spec:
![image](https://user-images.githubusercontent.com/1554850/106520975-4fc6f400-64bc-11eb-95f9-9be66aae019d.png)

**Comment by cjol** [comment]
Related to #407

**Comment by agalaguz** [comment]
hi Christopher, @cjol 
We were thinking about two options and hope you can help us to choose the better one. They are:

1. **Difficult one** - generate spec yaml file from data that we store in DB to perform API spec tests. We'll need to write some algorithm that will do it and this will require writing many tests, but the admin will get the latest generate ver of the spec. 
2. **Easier one** - once spec is uploaded to the platform store the spec file in the platform files too. So that no generation will be required. Ideally, there are no weaknesses here if we add together an ability to re-upload a spec (now it can be only removed) - so this way if the platform is setup admin will need to re-upload all specs and all existing test cases will keep their links to this spec and won't be any need to upload a newer ver of the spec. (so no need to run seeds and clear the db)

**Comment by cjol** [comment]
Option 2 is good!
