### ISSUE TITLE
Importing a test case when there is an error in the file

### ISSUE THREAD

**Issue by eudisley** [gsmainclusivetechlab/interop-test-platform#424]
High-level summary of the problem.

## Steps to reproduce

1. Importa a test case with a pre-existent slug
2. The platform will bring an error: The given data was invalid. Slug should be unique for different test cases groups.
3. Then you change the slug in the file, save it and go import again in the same screen
4. Then nothing happens after press import. 
5. Then the user has to: 1. go to another screen and go back to import test case. 2. Select another test case, do not import and then select the target test case again.

## Expected outcome

Import the test case after choosing it. 

## Actual outcome

Nothing happens. You click import and nothing happens, even with the loading bar appearing.

**Comment by cjol** [comment]
If I remember rightly, there is an error in the JavaScript console when you do this - something to do with the fact that the file hasn't changed.

**Comment by brunosmm** [comment]
Not sure if this is an error, I got this before so I was always adding the file in the input again before clicking import.

**Comment by cjol** [comment]
@brunosmm you think it's desirable behaviour to have to add the file twice when it's been changed?

**Comment by brunosmm** [comment]
For me it's looks like a normal behaviour...

Once you select a file from the browser it will load that state of the file, if you change it, you should reload it to the browser.

Probably the fix would be clear  the input file if you get an error once you click in import... Otherwise will force you to create something who take the file path and keep checking if the file changes. Do we really such advance thing for an admin functionality?

**Comment by cjol** [comment]
> Probably the fix would be clear the input file if you get an error once you click in import.

That's exactly what I am expecting. When we know there's an error, there's no point in keeping the file "loaded" so we should clear the input.

**Comment by SamyBouch** [comment]
Additionally it would be nice if there was some Twig template validation when importing a test case. For example in this test run https://compliance.mobilemoneyapi.io/sessions/8/test-cases/240/test-runs/266 the URL didn't generate a UUID because I had put `{ uuidv4() }` instead of `{{ uuidv4() }}` in the yaml file so it would be helpful if these sort of errors were flagged when importing.
