### ISSUE TITLE
Session Logs: Responses are not appearing in the list

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#459]
If you open a session and click on the logs button is not showing responses.
![image](https://user-images.githubusercontent.com/1554850/108242936-45e3f880-712c-11eb-8066-84eef00e1a0c.png)

## Steps to reproduce

1. Open a session
2. execute a test case
3. Check if the request/response is match in the step
4. Open the logs

## Expected outcome

All messages sent/received by the platform should be showed there.

## Actual outcome

At the moment is only showing requests.
https://compliance.mobilemoneyapi.io/sessions/6/message-log

**Comment by cjol** [comment]
Just realised that this is not a bug, but rather expected behaviour in the case of mismatched steps. When they are mismatched, there _is_ no response to show, because we were not able to reconcile a target component to generate a response from. If we did want to show responses here, it would just be the "Could not find matching test case" error message that gets sent to the SUT. Do you think that's useful to include?

We probably could show the _matched_ message responses here,  but I don't think it's a bug that they haven't been included - rather it would be a feature to add them in because I don't think they were ever present before!

**Comment by brunosmm** [comment]
You are right, I change it to roadmap item
