### ISSUE TITLE
Test Case Response not populated in TC Editor

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#501]
If you import a test case YAML, and then try to edit a step, the "response status" field is not correctly populated, and appears blank instead. 

## Steps to reproduce

1. Upload a YAML test case
2. Make it into a draft through the UI
3. Edit the test step (e.g. change the step pattern)
4. Try to save the step

## Expected outcome

Test response status is not empty, so test case step saves correctly.

## Actual outcome

Validation error on the test response status, which will be empty

**Comment by agalaguz** [comment]
Hi Bruno, @brunosmm 

I reproduced this validation error for "Repeat response status" rather than "Response status".
E.g. if test step does not include any "Repeat" conditions, the test case editor still says that "Repeat response status" is required.
![image](https://user-images.githubusercontent.com/16337770/112603965-5750ac80-8e1e-11eb-88c0-54294fd90e17.png)

Did I get it right? Could you please advise?

**Comment by cjol** [comment]
Yes, you are right sorry!
