### ISSUE TITLE
Display Image version in platform

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#511]
It would be useful to have a quick reference of the platform version in case of bugs or deployment of new code. We don't follow a strict versioning system, so we don't have a tidy version number to include. Instead, an environment variable should be set when the image is built, and this variable should be read to display a shortened version of the git sha in the platform footer (near the copyright notice).

**Comment by KisIrene** [comment]
@cesdias  @eudisley  What exactly should we display? Should we display a tag or a short commit ID?

**Comment by eudisley** [comment]
Hi @KisIrene, @cjol is not at GSMA. 
@cesdias created a versioning strategy for the Interoperability Platform. He can explain better.

**Comment by KisIrene** [comment]
@eudisley thanks, I got you) I changed the comment

**Comment by cesdias** [comment]
> Hi @KisIrene, @cjol is not at GSMA. @cesdias created a versioning strategy for the Interoperability Platform. He can explain better.

You must show the tag number if there's one associated with the branch/commit you are using to install/deploy ITP, otherwise just add the short commit ID as the version number.

For example, our last tagged version is `v1.6.2` related to the short commit ID `641e0f3`, so in this case you should display v1.6.2.
